name: Generate Datas

on:
  schedule: # execute every 12 hours
    - cron: "0 */12 * * *" # Ajustado o cron para a sintaxe correta
  workflow_dispatch:

jobs:
  build:
    name: Jobs to update datas
    runs-on: ubuntu-latest
    steps:
      # Snake Animation
      - name: Generate Snake Animation
        uses: Platane/snk@v2.0.0 # Certifique-se de usar a versão estável
        with:
          github_user_name: Gustavo4554
          outputs: dist/snake.svg

      - name: Deploy Snake Animation
        uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: 
